services:
  web-db:
    image: TODO
    env_file: .env
    networks:
      bridge-network:
        ipv4_address: $DBHOST
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
  web-lime:
    image: TODO
    env_file: .env
    environment:
      - APP_COLOR=$LIME_COLOR
    hostname: lime
    ports:
      - 8080:8080
    networks:
      - bridge-network
    depends_on:
      web-db:
        condition: service_healthy
  web-blue:
    image: TODO
    env_file: .env
    environment:
      - APP_COLOR=$BLUE_COLOR
    hostname: blue
    ports:
      - 8081:8080
    networks:
      - bridge-network
    depends_on:
      web-db:
        condition: service_healthy
  web-pink:
    image: TODO
    env_file: .env
    environment:
      - APP_COLOR=$PINK_COLOR
    hostname: pink
    ports:
      - 8082:8080
    networks:
      - bridge-network
    depends_on:
      web-db:
        condition: service_healthy
networks:
  bridge-network:
    driver: bridge
    ipam:
      config:
        - subnet: $SUBNET_RANGE
